services:
  ruta-consumer:
    build: .
    container_name: ruta-consumer
    ports:
      - "8082:8082"
    volumes:
      - ruta-data:/app/data
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    external: true

volumes:
  ruta-data:
